-- Words for Adjetives topic
INSERT INTO words (id, topic_id, name) VALUES (1, 1, 'Dazzling');
INSERT INTO words (id, topic_id, name) VALUES (2, 1, 'Fairly');
INSERT INTO words (id, topic_id, name) VALUES (3, 1, 'Big');
INSERT INTO words (id, topic_id, name) VALUES (4, 1, 'Curly');
INSERT INTO words (id, topic_id, name) VALUES (5, 1, 'Tall');
INSERT INTO words (id, topic_id, name) VALUES (6, 1, 'Spunky');
INSERT INTO words (id, topic_id, name) VALUES (7, 1, 'Silly');
INSERT INTO words (id, topic_id, name) VALUES (8, 1, 'Dapper');
INSERT INTO words (id, topic_id, name) VALUES (9, 1, 'Wacky');
INSERT INTO words (id, topic_id, name) VALUES (10, 1, 'Groovy');
INSERT INTO words (id, topic_id, name) VALUES (11, 1, 'Bubbly');
INSERT INTO words (id, topic_id, name) VALUES (12, 1, 'Personal');
INSERT INTO words (id, topic_id, name) VALUES (13, 1, 'Whimsical');
INSERT INTO words (id, topic_id, name) VALUES (14, 1, 'Gentle');
INSERT INTO words (id, topic_id, name) VALUES (15, 1, 'Calm');
INSERT INTO words (id, topic_id, name) VALUES (16, 1, 'Polite');
INSERT INTO words (id, topic_id, name) VALUES (17, 1, 'Neat');
INSERT INTO words (id, topic_id, name) VALUES (18, 1, 'Patient');
INSERT INTO words (id, topic_id, name) VALUES (19, 1, 'Careful');
INSERT INTO words (id, topic_id, name) VALUES (20, 1, 'Brave');
INSERT INTO words (id, topic_id, name) VALUES (21, 1, 'Curious');
INSERT INTO words (id, topic_id, name) VALUES (22, 1, 'Trustworthy');
INSERT INTO words (id, topic_id, name) VALUES (23, 1, 'Humble');
INSERT INTO words (id, topic_id, name) VALUES (24, 1, 'Clever');
INSERT INTO words (id, topic_id, name) VALUES (25, 1, 'Funky');

-- Words for Animal Names topic
INSERT INTO words (id, topic_id, name) VALUES (26, 2, 'Lion');
INSERT INTO words (id, topic_id, name) VALUES (27, 2, 'Tiger');
INSERT INTO words (id, topic_id, name) VALUES (28, 2, 'Elephant');
INSERT INTO words (id, topic_id, name) VALUES (29, 2, 'Giraffe');
INSERT INTO words (id, topic_id, name) VALUES (30, 2, 'Zebra');
INSERT INTO words (id, topic_id, name) VALUES (31, 2, 'Kangaroo');
INSERT INTO words (id, topic_id, name) VALUES (32, 2, 'Panda');
INSERT INTO words (id, topic_id, name) VALUES (33, 2, 'Koala');
INSERT INTO words (id, topic_id, name) VALUES (34, 2, 'Cheetah');
INSERT INTO words (id, topic_id, name) VALUES (35, 2, 'Penguin');
INSERT INTO words (id, topic_id, name) VALUES (36, 2, 'Dolphin');
INSERT INTO words (id, topic_id, name) VALUES (37, 2, 'Whale');
INSERT INTO words (id, topic_id, name) VALUES (38, 2, 'Frog');
INSERT INTO words (id, topic_id, name) VALUES (39, 2, 'Crocodile');
INSERT INTO words (id, topic_id, name) VALUES (40, 2, 'Hedgehog');
INSERT INTO words (id, topic_id, name) VALUES (41, 2, 'Ostrich');
INSERT INTO words (id, topic_id, name) VALUES (42, 2, 'Lemur');
INSERT INTO words (id, topic_id, name) VALUES (43, 2, 'Sloth');
INSERT INTO words (id, topic_id, name) VALUES (44, 2, 'Octopus');
INSERT INTO words (id, topic_id, name) VALUES (45, 2, 'Parrot');
INSERT INTO words (id, topic_id, name) VALUES (46, 2, 'Squirrel');
INSERT INTO words (id, topic_id, name) VALUES (47, 2, 'Bear');
INSERT INTO words (id, topic_id, name) VALUES (48, 2, 'Rabbit');
INSERT INTO words (id, topic_id, name) VALUES (49, 2, 'Mongoose');
INSERT INTO words (id, topic_id, name) VALUES (50, 2, 'Tortoise');

-- Words for Basketball teams topic
INSERT INTO words (id, topic_id, name) VALUES (51, 3, 'Los Angeles Lakers');
INSERT INTO words (id, topic_id, name) VALUES (52, 3, 'Chicago Bulls');
INSERT INTO words (id, topic_id, name) VALUES (53, 3, 'Golden State Warriors');
INSERT INTO words (id, topic_id, name) VALUES (54, 3, 'Boston Celtics');
INSERT INTO words (id, topic_id, name) VALUES (55, 3, 'Miami Heat');
INSERT INTO words (id, topic_id, name) VALUES (56, 3, 'San Antonio Spurs');
INSERT INTO words (id, topic_id, name) VALUES (57, 3, 'Brooklyn Nets');
INSERT INTO words (id, topic_id, name) VALUES (58, 3, 'Dallas Mavericks');
INSERT INTO words (id, topic_id, name) VALUES (59, 3, 'Houston Rockets');
INSERT INTO words (id, topic_id, name) VALUES (60, 3, 'Toronto Raptors');
INSERT INTO words (id, topic_id, name) VALUES (61, 3, 'Philadelphia 76ers');
INSERT INTO words (id, topic_id, name) VALUES (62, 3, 'Denver Nuggets');
INSERT INTO words (id, topic_id, name) VALUES (63, 3, 'Utah Jazz');
INSERT INTO words (id, topic_id, name) VALUES (64, 3, 'Portland Trail Blazers');
INSERT INTO words (id, topic_id, name) VALUES (65, 3, 'Atlanta Hawks');
INSERT INTO words (id, topic_id, name) VALUES (66, 3, 'Phoenix Suns');
INSERT INTO words (id, topic_id, name) VALUES (67, 3, 'Indiana Pacers');
INSERT INTO words (id, topic_id, name) VALUES (68, 3, 'Charlotte Hornets');
INSERT INTO words (id, topic_id, name) VALUES (69, 3, 'New Orleans Pelicans');
INSERT INTO words (id, topic_id, name) VALUES (70, 3, 'Memphis Grizzlies');
INSERT INTO words (id, topic_id, name) VALUES (71, 3, 'Sacramento Kings');
INSERT INTO words (id, topic_id, name) VALUES (72, 3, 'Oklahoma City Thunder');
INSERT INTO words (id, topic_id, name) VALUES (73, 3, 'Milwaukee Bucks');
INSERT INTO words (id, topic_id, name) VALUES (74, 3, 'Washington Wizards');
INSERT INTO words (id, topic_id, name) VALUES (75, 3, 'Minnesota Timberwolves');

-- Words for Color names topic
INSERT INTO words (id, topic_id, name) VALUES (76, 4, 'Red');
INSERT INTO words (id, topic_id, name) VALUES (77, 4, 'Blue');
INSERT INTO words (id, topic_id, name) VALUES (78, 4, 'Green');
INSERT INTO words (id, topic_id, name) VALUES (79, 4, 'Yellow');
INSERT INTO words (id, topic_id, name) VALUES (80, 4, 'Orange');
INSERT INTO words (id, topic_id, name) VALUES (81, 4, 'Purple');
INSERT INTO words (id, topic_id, name) VALUES (82, 4, 'Pink');
INSERT INTO words (id, topic_id, name) VALUES (83, 4, 'Brown');
INSERT INTO words (id, topic_id, name) VALUES (84, 4, 'Black');
INSERT INTO words (id, topic_id, name) VALUES (85, 4, 'White');
INSERT INTO words (id, topic_id, name) VALUES (86, 4, 'Cyan');
INSERT INTO words (id, topic_id, name) VALUES (87, 4, 'Magenta');
INSERT INTO words (id, topic_id, name) VALUES (88, 4, 'Violet');
INSERT INTO words (id, topic_id, name) VALUES (89, 4, 'Indigo');
INSERT INTO words (id, topic_id, name) VALUES (90, 4, 'Gray');
INSERT INTO words (id, topic_id, name) VALUES (91, 4, 'Teal');
INSERT INTO words (id, topic_id, name) VALUES (92, 4, 'Maroon');
INSERT INTO words (id, topic_id, name) VALUES (93, 4, 'Olive');
INSERT INTO words (id, topic_id, name) VALUES (94, 4, 'Navy');
INSERT INTO words (id, topic_id, name) VALUES (95, 4, 'Lime');
INSERT INTO words (id, topic_id, name) VALUES (96, 4, 'Coral');
INSERT INTO words (id, topic_id, name) VALUES (97, 4, 'Peach');
INSERT INTO words (id, topic_id, name) VALUES (98, 4, 'Lavender');
INSERT INTO words (id, topic_id, name) VALUES (99, 4, 'Mint');
INSERT INTO words (id, topic_id, name) VALUES (100, 4, 'Crimson');

-- Words for Harry Potter spells topic
INSERT INTO words (id, topic_id, name) VALUES (101, 5, 'Expelliarmus');
INSERT INTO words (id, topic_id, name) VALUES (102, 5, 'Lumos');
INSERT INTO words (id, topic_id, name) VALUES (103, 5, 'Alohomora');
INSERT INTO words (id, topic_id, name) VALUES (104, 5, 'Accio');
INSERT INTO words (id, topic_id, name) VALUES (105, 5, 'Stupefy');
INSERT INTO words (id, topic_id, name) VALUES (106, 5, 'Avada Kedavra');
INSERT INTO words (id, topic_id, name) VALUES (107, 5, 'Expecto Patronum');
INSERT INTO words (id, topic_id, name) VALUES (108, 5, 'Riddikulus');
INSERT INTO words (id, topic_id, name) VALUES (109, 5, 'Obliviate');
INSERT INTO words (id, topic_id, name) VALUES (110, 5, 'Petrificus Totalus');
INSERT INTO words (id, topic_id, name) VALUES (111, 5, 'Wingardium Leviosa');
INSERT INTO words (id, topic_id, name) VALUES (112, 5, 'Reparo');
INSERT INTO words (id, topic_id, name) VALUES (113, 5, 'Nox');
INSERT INTO words (id, topic_id, name) VALUES (114, 5, 'Imperio');
INSERT INTO words (id, topic_id, name) VALUES (115, 5, 'Crucio');
INSERT INTO words (id, topic_id, name) VALUES (116, 5, 'Muffliato');
INSERT INTO words (id, topic_id, name) VALUES (117, 5, 'Incendio');
INSERT INTO words (id, topic_id, name) VALUES (118, 5, 'Accio');
INSERT INTO words (id, topic_id, name) VALUES (119, 5, 'Aguamenti');
INSERT INTO words (id, topic_id, name) VALUES (120, 5, 'Diffindo');
INSERT INTO words (id, topic_id, name) VALUES (121, 5, 'Expulso');
INSERT INTO words (id, topic_id, name) VALUES (122, 5, 'Sectumsempra');
INSERT INTO words (id, topic_id, name) VALUES (123, 5, 'Silencio');
INSERT INTO words (id, topic_id, name) VALUES (124, 5, 'Stupefy');
INSERT INTO words (id, topic_id, name) VALUES (125, 5, 'Piertotum Locomotor');

-- Words for Sport names topic
INSERT INTO words (id, topic_id, name) VALUES (126, 6, 'Soccer');
INSERT INTO words (id, topic_id, name) VALUES (127, 6, 'Basketball');
INSERT INTO words (id, topic_id, name) VALUES (128, 6, 'Tennis');
INSERT INTO words (id, topic_id, name) VALUES (129, 6, 'Baseball');
INSERT INTO words (id, topic_id, name) VALUES (130, 6, 'Volleyball');
INSERT INTO words (id, topic_id, name) VALUES (131, 6, 'Rugby');
INSERT INTO words (id, topic_id, name) VALUES (132, 6, 'Hockey');
INSERT INTO words (id, topic_id, name) VALUES (133, 6, 'Cricket');
INSERT INTO words (id, topic_id, name) VALUES (134, 6, 'Golf');
INSERT INTO words (id, topic_id, name) VALUES (135, 6, 'Swimming');
INSERT INTO words (id, topic_id, name) VALUES (136, 6, 'Running');
INSERT INTO words (id, topic_id, name) VALUES (137, 6, 'Cycling');
INSERT INTO words (id, topic_id, name) VALUES (138, 6, 'Boxing');
INSERT INTO words (id, topic_id, name) VALUES (139, 6, 'Gymnastics');
INSERT INTO words (id, topic_id, name) VALUES (140, 6, 'Surfing');
INSERT INTO words (id, topic_id, name) VALUES (141, 6, 'Table Tennis');
INSERT INTO words (id, topic_id, name) VALUES (142, 6, 'Badminton');
INSERT INTO words (id, topic_id, name) VALUES (143, 6, 'Wrestling');
INSERT INTO words (id, topic_id, name) VALUES (144, 6, 'Motorsport');
INSERT INTO words (id, topic_id, name) VALUES (145, 6, 'Skating');
INSERT INTO words (id, topic_id, name) VALUES (146, 6, 'Fencing');
INSERT INTO words (id, topic_id, name) VALUES (147, 6, 'Skiing');
INSERT INTO words (id, topic_id, name) VALUES (148, 6, 'Archery');
INSERT INTO words (id, topic_id, name) VALUES (149, 6, 'Equestrian');
INSERT INTO words (id, topic_id, name) VALUES (150, 6, 'Rowing');

-- Words for Minecraft mobs topic
INSERT INTO words (id, topic_id, name) VALUES (151, 7, 'Creeper');
INSERT INTO words (id, topic_id, name) VALUES (152, 7, 'Zombie');
INSERT INTO words (id, topic_id, name) VALUES (153, 7, 'Skeleton');
INSERT INTO words (id, topic_id, name) VALUES (154, 7, 'Enderman');
INSERT INTO words (id, topic_id, name) VALUES (155, 7, 'Spider');
INSERT INTO words (id, topic_id, name) VALUES (156, 7, 'Ghast');
INSERT INTO words (id, topic_id, name) VALUES (157, 7, 'Blaze');
INSERT INTO words (id, topic_id, name) VALUES (158, 7, 'Witch');
INSERT INTO words (id, topic_id, name) VALUES (159, 7, 'Silverfish');
INSERT INTO words (id, topic_id, name) VALUES (160, 7, 'Ender Dragon');
INSERT INTO words (id, topic_id, name) VALUES (161, 7, 'Wither');
INSERT INTO words (id, topic_id, name) VALUES (162, 7, 'Panda');
INSERT INTO words (id, topic_id, name) VALUES (163, 7, 'Villager');
INSERT INTO words (id, topic_id, name) VALUES (164, 7, 'Wolf');
INSERT INTO words (id, topic_id, name) VALUES (165, 7, 'Ocelot');
INSERT INTO words (id, topic_id, name) VALUES (166, 7, 'Horse');
INSERT INTO words (id, topic_id, name) VALUES (167, 7, 'Parrot');
INSERT INTO words (id, topic_id, name) VALUES (168, 7, 'Fox');
INSERT INTO words (id, topic_id, name) VALUES (169, 7, 'Bee');
INSERT INTO words (id, topic_id, name) VALUES (170, 7, 'Dolphin');
INSERT INTO words (id, topic_id, name) VALUES (171, 7, 'Axolotl');
INSERT INTO words (id, topic_id, name) VALUES (172, 7, 'Squid');
INSERT INTO words (id, topic_id, name) VALUES (173, 7, 'Bat');
INSERT INTO words (id, topic_id, name) VALUES (174, 7, 'Guardian');
INSERT INTO words (id, topic_id, name) VALUES (175, 7, 'Ravager');
